export type FluidConfig = {
  TEXTURE_DOWNSAMPLE: number;
  DENSITY_DISSIPATION: number;
  VELOCITY_DISSIPATION: number;
  PRESSURE_DISSIPATION: number;
  PRESSURE_ITERATIONS: number;
  CURL: number;
  SPLAT_RADIUS: number;
  WALL_THICKNESS: number;
  WALL_RESTITUTION: number;
  WALL_FRICTION: number;
};

export const defaultFluidConfig: FluidConfig = {
  TEXTURE_DOWNSAMPLE: 1,
  DENSITY_DISSIPATION: 0.98,
  VELOCITY_DISSIPATION: 0.98,
  PRESSURE_DISSIPATION: 0.8,
  PRESSURE_ITERATIONS: 20,
  CURL: 30,
  SPLAT_RADIUS: 0.5,
  WALL_THICKNESS: 2,
  WALL_RESTITUTION: 0.9,
  WALL_FRICTION: 0.05,
};
